version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /backend
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: backend/requirements
    schedule:
      interval: "monthly"
    labels: [ ]
    ignore:
      - dependency-name: "*"

  - package-ecosystem: npm
    directory: /client
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker
    open-pull-requests-limit: 0
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /documentation
    open-pull-requests-limit: 0
    schedule:
      interval: daily
