version: '3'

services:
  globaleaks:
    build: .
    restart: unless-stopped
    container_name: globaleaks
    network_mode: bridge
    volumes:
      - globaleaks:/var/globaleaks
    ports:
      - 80:8080
      - 443:8443

volumes:
  globaleaks: