name: Build

on: [ push, pull_request ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  run_build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Install git
        run: |
          sudo apt-get update -q
          sudo apt-get install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run_build.sh
