name: Tests

on: [ push, pull_request ]

# Declare default permissions as read only.
permissions: read-all

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache pip dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install git
        run: |
          sudo apt-get update -q
          sudo apt-get install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run_tests.sh
